# Generated by Django 4.1 on 2022-09-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                ("rollno", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("class_section", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Attendants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendants", models.BooleanField()),
                ("subject", models.CharField(max_length=10)),
                ("period_no", models.IntegerField()),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.student",
                    ),
                ),
            ],
        ),
    ]
