# Generated by Django 4.1 on 2022-09-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Attendants",
            new_name="Attendant",
        ),
    ]
