# Generated by Django 4.1 on 2022-09-04 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_rename_attendants_attendant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "classname",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.student",
                    ),
                ),
            ],
        ),
    ]
