# Generated by Django 4.1 on 2022-09-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_remove_class_student_alter_attendant_attendants"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="teacher.student",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendant",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="teacher.student"
            ),
        ),
    ]
