# Generated by Django 4.1 on 2022-09-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0005_class_student_alter_attendant_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="student",
        ),
        migrations.AddField(
            model_name="class",
            name="student",
            field=models.ManyToManyField(to="teacher.student"),
        ),
    ]
