# Generated by Django 4.1 on 2022-09-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0007_rename_class_classe"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Classe",
            new_name="Class",
        ),
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name": "class", "verbose_name_plural": "classes"},
        ),
    ]
